# Shell variables
# Generated by 'wal'
wallpaper='/home/manu/wallpaper/corals-fish-underwater.jpg'

# Special
background='#14151e'
foreground='#cde0e7'
cursor='#cde0e7'

# Colors
color0='#14151e'
color1='#837C8F'
color2='#7B859E'
color3='#7EA3C1'
color4='#8896B2'
color5='#8FB1D6'
color6='#94C9E5'
color7='#cde0e7'
color8='#8f9ca1'
color9='#837C8F'
color10='#7B859E'
color11='#7EA3C1'
color12='#8896B2'
color13='#8FB1D6'
color14='#94C9E5'
color15='#cde0e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
