foreground   #cde0e7
background   #14151e
cursor       #cde0e7

color0       #14151e
color8       #8f9ca1
color1       #837C8F
color9       #837C8F
color2       #7B859E
color10      #7B859E
color3       #7EA3C1
color11      #7EA3C1
color4       #8896B2
color12      #8896B2
color5       #8FB1D6
color13      #8FB1D6
color6       #94C9E5
color14      #94C9E5
color7       #cde0e7
color15      #cde0e7
